import { Brand } from "@/types/brand";

const brandsData: Brand[] = [
  {
    id: 1,
    name: "Enterprise Applications",
    href: "#",
    image: "/images/brands/generic.svg",
    imageLight: "/images/brands/generic-light.svg",
  },
  {
    id: 2,
    name: "ERP",
    href: "#",
    image: "/images/brands/generic.svg",
    imageLight: "/images/brands/generic-light.svg",
  },
  {
    id: 3,
    name: "Financial Management",
    href: "#",
    image: "/images/brands/generic.svg",
    imageLight: "/images/brands/generic-light.svg",
  },
  {
    id: 4,
    name: "Supply Chain Management",
    href: "#",
    image: "/images/brands/generic.svg",
    imageLight: "/images/brands/generic-light.svg",
  },
  {
    id: 5,
    name: "Asset Management",
    href: "#",
    image: "/images/brands/generic.svg",
    imageLight: "/images/brands/generic-light.svg",
  },
  {
    id: 6,
    name: "Fleet Management",
    href: "#",
    image: "/images/brands/generic.svg",
    imageLight: "/images/brands/generic-light.svg",
  },
  {
    id: 7,
    name: "HR Software",
    href: "#",
    image: "/images/brands/generic.svg",
    imageLight: "/images/brands/generic-light.svg",
  },
  {
    id: 8,
    name: "eLearning Software",
    href: "#",
    image: "/images/brands/generic.svg",
    imageLight: "/images/brands/generic-light.svg",
  },
  {
    id: 9,
    name: "eCommerce",
    href: "#",
    image: "/images/brands/generic.svg",
    imageLight: "/images/brands/generic-light.svg",
  },
  {
    id: 10,
    name: "Mobile Apps",
    href: "#",
    image: "/images/brands/generic.svg",
    imageLight: "/images/brands/generic-light.svg",
  },
  {
    id: 11,
    name: "Content Management",
    href: "#",
    image: "/images/brands/generic.svg",
    imageLight: "/images/brands/generic-light.svg",
  },
  {
    id: 12,
    name: "Document Management",
    href: "#",
    image: "/images/brands/generic.svg",
    imageLight: "/images/brands/generic-light.svg",
  },
  {
    id: 13,
    name: "CRM",
    href: "#",
    image: "/images/brands/generic.svg",
    imageLight: "/images/brands/generic-light.svg",
  },
  {
    id: 14,
    name: "Marketing & Advertising",
    href: "#",
    image: "/images/brands/generic.svg",
    imageLight: "/images/brands/generic-light.svg",
  },
  {
    id: 15,
    name: "Web Portals",
    href: "#",
    image: "/images/brands/generic.svg",
    imageLight: "/images/brands/generic-light.svg",
  },
  {
    id: 16,
    name: "Data Analytics",
    href: "#",
    image: "/images/brands/generic.svg",
    imageLight: "/images/brands/generic-light.svg",
  },
  {
    id: 17,
    name: "Imports",
    href: "#",
    image: "/images/brands/generic.svg",
    imageLight: "/images/brands/generic-light.svg",
  },
  {
    id: 18,
    name: "Exports",
    href: "#",
    image: "/images/brands/generic.svg",
    imageLight: "/images/brands/generic-light.svg",
  },
];

export default brandsData;
